name: turn on/off ec2 instance

on:
  # If you want to trigger this on push to a branch uncomment below
  # push:
  #   branches: [main]


  workflow_dispatch:
    inputs:
      state:
        description: 'Specify whether to start or stop the EC2 instance'
        required: true
        type: string

        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'
      

      - name: Start or Stop EC2 Instance
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.state }}" == "start" ]; then
              aws ec2 start-instances --instance-ids i-011db630cc4ed5181
            elif [ "${{ github.event.inputs.state }}" == "stop" ]; then
              aws ec2 stop-instances --instance-ids i-011db630cc4ed5181
            else
              echo "Invalid action specified"
              exit 1
            fi
          fi
