name: turn on/off ec2 instance

on:
  # If you want to trigger this on push to a branch uncomment below
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      action:
        description: 'Specify whether to start or stop the EC2 instance'
        required: true
        default: 'start'  # You can set a default value if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::1234567890:role/example-role
          role-session-name: samplerolesession
          aws-region: ap-south-1

      - name: Start or Stop EC2 Instance
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.action }}" == "start" ]; then
              aws ec2 start-instances --instance-ids i-09a6d11103121b3f5
            elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
              aws ec2 stop-instances --instance-ids i-09a6d11103121b3f5
            else
              echo "Invalid action specified"
              exit 1
            fi
          fi
